### ISSUE TITLE
Why not error first callbacks?

### ISSUE THREAD

**Issue by yktv4** [kraken-io/kraken-node#16]
Hey guys,

Thank you for your product, it's great and a pleasure to use. One small question though is why you don't follow a fundamental nodejs technique of error first callbacks (more info here: http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/)? Whole node ecosystem is built atop of that principle including `fs` and `request` packages this repo depends on.

I could make a pull request, but that would break the backwards compatibility. Though if a release with error first callbacks would have a new major version, you could probably avoid most of unwanted breakages because of npm's `^` version locker.

**Comment by kingr** [comment]
I also discovered this, it's quite annoying that you have to check if 'status is 'false'. This is a joke.

The author of this Library does not care about giving any feedback to the community since I've been using this product the past year. 

I'm tired of the random issues I've had with this library/product and have found a better Free alternative 
https://github.com/lovell/sharp

Closing my paid account.

**Comment by chemitaxis** [comment]
This is terrible... nobody is updating this???

**Comment by ustuehler** [comment]
Apologies! Error-first callbacks have finally been released officially in version 0.4.0.

Release 0.3.5 accidentally included this breaking change already. but has been properly deprecated and superseded by version 0.3.6. If anyone depends on the legacy callback semantics, use `^0.3.6` in package.json; otherwise, please update package.json to `^0.4.0`.
